"""event photo_url

Revision ID: 89836b9e4430
Revises: 5633aed3de02
Create Date: 2025-08-19 09:54:44.920496+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89836b9e4430'
down_revision: Union[str, None] = '5633aed3de02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('photo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'photo_url')
    # ### end Alembic commands ###
