"""events & participants

Revision ID: 2ecff9076dc0
Revises: 93c1e333babc
Create Date: 2025-08-15 08:02:44.503770+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ecff9076dc0'
down_revision: Union[str, None] = '93c1e333babc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gender_restriction', sa.Enum('male', 'female', 'all', name='gender_restriction'), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'past', name='event_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_participants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('joined', 'left', 'no_show', name='participant_status'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_user')
    )
    op.create_index("idx_events_city_date", "events", ["city", "date_time"])
    op.create_index("idx_events_city_gender", "events", ["city", "gender_restriction"])
    op.create_index("idx_ep_event", "event_participants", ["event_id"])
    op.create_index("idx_ep_user", "event_participants", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ep_user", table_name="event_participants")
    op.drop_index("idx_ep_event", table_name="event_participants")
    op.drop_index("idx_events_city_gender", table_name="events")
    op.drop_index("idx_events_city_date", table_name="events")
    op.drop_table('event_participants')
    op.drop_table('events')
    # ### end Alembic commands ###
