"""events & participants

Revision ID: 554371a5cc4f
Revises: 2ecff9076dc0
Create Date: 2025-08-15 08:08:27.327858+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554371a5cc4f'
down_revision: Union[str, None] = '2ecff9076dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_events_city_date ON events (city, date_time)"
    )
    op.create_index("idx_events_city_gender", "events", ["city", "gender_restriction"])
    op.create_index("idx_ep_event", "event_participants", ["event_id"])
    op.create_index("idx_ep_user", "event_participants", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ep_user", table_name="event_participants")
    op.drop_index("idx_ep_event", table_name="event_participants")
    op.drop_index("idx_events_city_gender", table_name="events")
    op.execute("DROP INDEX IF EXISTS idx_events_city_date")
    # ### end Alembic commands ###
