"""user gender

Revision ID: d9f96da38247
Revises: 554371a5cc4f
Create Date: 2025-08-17 16:50:36.990463+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f96da38247'
down_revision: Union[str, None] = '554371a5cc4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_gender = sa.Enum('male', 'female', 'unknown', name='user_gender')
    user_gender.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('gender', user_gender, nullable=True))
    op.execute("UPDATE users SET gender = 'unknown'::user_gender")
    op.alter_column('users', 'gender', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender', nullable=True)
    op.drop_column('users', 'gender')
    user_gender = sa.Enum('male', 'female', 'unknown', name='user_gender')
    user_gender.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
